import express from "express";
import countryController from "./country.controller";
const router = express.Router();
router.post("/store", countryController.Store);
router.get("/", countryController.Index);
router.get("/search", countryController.Search);
router.get("/import", countryController.import);
router.get("/export", countryController.export);
router.get("/export-template", countryController.exportTemplate);
router.get("/:id", countryController.Show);
router.put("/:id", countryController.Update);
router.delete("/:id", countryController.Delete);
router.patch("/:id/enable", countryController.activate);
router.patch("/:id/disable", countryController.deactivate);
export default router;
