import { ISearchParams } from "@/database/apis/apis-db-interface";
import { datatypes } from "../definitions/constants/data-types";
import { searchTypes } from "../definitions/constants/search-types";

export const defaultSearchParams: ISearchParams[] = [
    {
        title: "id",
        value: "id",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "is_deleted",
        value: "is_deleted",
        allowed_values: [],
        datatype: datatypes.Boolean,
        search_type: searchTypes.Exact,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "created_at_gte",
        value: "created_at",
        allowed_values: [],
        datatype: datatypes.Date,
        search_type: searchTypes.GreaterThan,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "created_at_lte",
        value: "created_at",
        allowed_values: [],
        datatype: datatypes.Date,
        search_type: searchTypes.LessThan,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "updated_at_gte",
        value: "updated_at",
        allowed_values: [],
        datatype: datatypes.Date,
        search_type: searchTypes.GreaterThan,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "updated_at_lte",
        value: "updated_at",
        allowed_values: [],
        datatype: datatypes.Date,
        search_type: searchTypes.LessThan,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "deleted_at_gte",
        value: "deleted_at",
        allowed_values: [],
        datatype: datatypes.Date,
        search_type: searchTypes.GreaterThan,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "deleted_at_lte",
        value: "deleted_at",
        allowed_values: [],
        datatype: datatypes.Date,
        search_type: searchTypes.LessThan,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "is_active",
        value: "is_active",
        allowed_values: [],
        datatype: datatypes.Boolean,
        search_type: searchTypes.Exact,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "created_by_id",
        value: "created_by._id",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "created_by_name_like",
        value: "created_by.first_name",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "created_by_role_like",
        value: "created_by.role",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "created_by_email_like",
        value: "created_by.email",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "updated_by_id",
        value: "updated_by._id",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "updated_by_name_like",
        value: "updated_by.first_name",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "updated_by_role_like",
        value: "updated_by.role",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "updated_by_email_like",
        value: "updated_by.email",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "deleted_by_id",
        value: "deleted_by._id",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "deleted_by_name_like",
        value: "deleted_by.first_name",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "deleted_by_role_like",
        value: "deleted_by.role",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "deleted_by_email_like",
        value: "deleted_by.email",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "status_id",
        value: "status_id._id",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
    {
        title: "status_title_like",
        value: "status_id.title",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        admin_access: true,
        user_access: true,
        employee_access: true,
    },
];
