import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { AccessType, IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/authentication-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";

const authenticationApiData: IAPI[] = [
  {
    activity_type: activityTypes.Send,
    module: moduleTypes.Authentication,
    activity_name: activityName.SentOtp,
    activity_code: activityCode.SentOtp,
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/sent-otp",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {
      admin_access: { type: AccessType.ALL, keys: [] },
    },
    control_params: [],
    payload_params: [],
    required_authentication: false,
    admin_access: true,
    user_access: false,
    employee_access: true,
  },
  {
    activity_type: activityTypes.Login,
    module: moduleTypes.Authentication,
    activity_name: activityName.VerifyOtp,
    activity_code: activityCode.VerifyOtp,
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/verify-otp/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {
      admin_access: { type: AccessType.ALL, keys: [] },
    },
    control_params: [],
    payload_params: [],
    required_authentication: false,
    admin_access: true,
    user_access: false,
    employee_access: true,
  },
  {
    activity_type: activityTypes.Refresh,
    module: moduleTypes.Authentication,
    activity_name: activityName.RefreshToken,
    activity_code: activityCode.refreshToken,
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/refresh-token",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {
      admin_access: { type: AccessType.ALL, keys: [] },
    },
    control_params: [],
    payload_params: [],
    required_authentication: false,
    admin_access: true,
    user_access: false,
    employee_access: true,
  },
  {
    activity_type: activityTypes.Login,
    module: moduleTypes.Authentication,
    activity_name: activityName.Login,
    activity_code: activityCode.Login,
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/admin-login",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {
      admin_access: { type: AccessType.ALL, keys: [] },
    },
    control_params: [],
    payload_params: [],
    required_authentication: false,
    admin_access: true,
    user_access: false,
    employee_access: true,
  },
  {
    activity_type: activityTypes.Login,
    module: moduleTypes.Authentication,
    activity_name: activityName.Login,
    activity_code: activityCode.Login,
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/login",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {
      admin_access: { type: AccessType.ALL, keys: [] },
    },
    control_params: [],
    payload_params: [],
    required_authentication: false,
    admin_access: true,
    user_access: false,
    employee_access: true,
  },
  {
    activity_type: activityTypes.Logout,
    module: moduleTypes.Authentication,
    activity_name: "Logout",
    activity_code: "logout",
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/logout",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {
      admin_access: { type: AccessType.ALL, keys: [] },
    },
    control_params: [],
    payload_params: [],
    required_authentication: true,
    admin_access: true,
    user_access: true,
    employee_access: true,
  },
  {
    activity_type: activityTypes.Logout,
    module: moduleTypes.Authentication,
    activity_name: "Logout All",
    activity_code: "logout_all",
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/logout-all",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {
      admin_access: { type: AccessType.ALL, keys: [] },
    },
    control_params: [],
    payload_params: [],
    required_authentication: true,
    admin_access: true,
    user_access: true,
    employee_access: true,
  },
];

export default authenticationApiData;
