import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { AccessType, IAPI } from "../../../../utils/interfaces/api.interface";
import {
    activityCode,
    activityName,
} from "../../activities/priority-activities";
import { searchTypes } from "../../../../utils/definitions/constants/search-types";
import { declaimerKeys } from "../../../../resources/v1/masters/declaimers/declaimer.validator";

const priorityApiData: IAPI[] = [
    // create status
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Priorities,
        activity_name: activityName.createPriority,
        activity_code: activityCode.createPriority,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/priorities",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [
            {
                key: "key",
                value: "enum (priorityKeys)",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "title",
                value: "string",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "content",
                value: "string",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "language",
                value: "string (2-letter code, default: en)",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "country",
                value: "string (2-letter ISO) | null",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "metadata",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        admin_access: true,
        user_access: false,
        employee_access: false,
        required_authentication: true,
    },

    // list status
    {
        activity_type: activityTypes.List,
        module: moduleTypes.Priorities,
        activity_name: activityName.listPriority,
        activity_code: activityCode.listPriority,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/priorities",
        status: true,
        form_params: [],
        search_params: [
            {
                title: "key",
                value: "key",
                datatype: datatypes.String,
                search_type: searchTypes.Partial,
                allowed_values: Object.values(declaimerKeys),
                is_active: true,
                admin_access: true,
                user_access: true,
                employee_access: true,
            },
            {
                title: "language",
                value: "language",
                datatype: datatypes.String,
                search_type: searchTypes.Partial,
                allowed_values: [],
                is_active: true,
                admin_access: true,
                user_access: true,
                employee_access: true,
            },
            {
                title: "country",
                value: "country",
                datatype: datatypes.String,
                search_type: searchTypes.Partial,
                allowed_values: [],
                is_active: true,
                admin_access: true,
                user_access: true,
                employee_access: true,
            },
            {
                title: "version",
                value: "version",
                datatype: datatypes.Number,
                search_type: searchTypes.Exact,
                allowed_values: [],
                is_active: true,
                admin_access: true,
                user_access: true,
                employee_access: true,
            },
            {
                title: "is_latest",
                value: "is_latest",
                datatype: datatypes.Boolean,
                search_type: searchTypes.Exact,
                allowed_values: ["true", "false"],
                is_active: true,
                admin_access: true,
                user_access: true,
                employee_access: true,
            },
            {
                title: "is_active",
                value: "is_active",
                datatype: datatypes.Boolean,
                search_type: searchTypes.Exact,
                allowed_values: ["true", "false"],
                is_active: true,
                admin_access: true,
                user_access: true,
                employee_access: true,
            },
        ],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [],
        admin_access: true,
        user_access: true,
        employee_access: true,
        required_authentication: true,
    },

    // update status
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Priorities,
        activity_name: activityName.updatePriority,
        activity_code: activityCode.updatePriority,
        activity_method: apiMethods.PUT,
        url: "/api/v1/masters/priorities/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [
            {
                key: "title",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "content",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "metadata",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        admin_access: true,
        user_access: false,
        employee_access: false,
        required_authentication: true,
    },

    // delete status
    {
        activity_type: activityTypes.Delete,
        module: moduleTypes.Priorities,
        activity_name: activityName.deletePriority,
        activity_code: activityCode.deletePriority,
        activity_method: apiMethods.DELETE,
        url: "/api/v1/masters/priorities/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [],
        admin_access: true,
        user_access: false,
        employee_access: false,
        required_authentication: true,
    },
    // activate status
    {
        activity_type: activityTypes.Activate,
        module: moduleTypes.Priorities,
        activity_name: activityName.activatePriority,
        activity_code: activityCode.activatePriority,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/priorities/:id/activate",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [],
        admin_access: true,
        user_access: false,
        employee_access: false,
        required_authentication: true,
    },
    // deactivate status
    {
        activity_type: activityTypes.Deactivate,
        module: moduleTypes.Priorities,
        activity_name: activityName.deactivatePriority,
        activity_code: activityCode.deactivatePriority,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/priorities/:id/deactivate",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [],
        admin_access: true,
        user_access: false,
        employee_access: false,
        required_authentication: true,
    },
    // show status
    {
        activity_type: activityTypes.Show,
        module: moduleTypes.Priorities,
        activity_name: activityName.showPriority,
        activity_code: activityCode.showPriority,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/priorities/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [],
        admin_access: true,
        user_access: true,
        employee_access: true,
        required_authentication: true,
    },
    // import status
    {
        activity_type: activityTypes.Import,
        module: moduleTypes.Priorities,
        activity_name: activityName.importPriority,
        activity_code: activityCode.importPriority,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/priorities/import",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [],
        admin_access: true,
        user_access: false,
        employee_access: false,
        required_authentication: true,
    },
    // export status
    {
        activity_type: activityTypes.Export,
        module: moduleTypes.Priorities,
        activity_name: activityName.exportPriority,
        activity_code: activityCode.exportPriority,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/priorities/export",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [],
        admin_access: true,
        user_access: false,
        employee_access: false,
        required_authentication: true,
    },
    {
        activity_type: activityTypes.Export,
        module: moduleTypes.Priorities,
        activity_name: activityName.exportTemplatePriority,
        activity_code: activityCode.exportTemplatePriority,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/priorities/export-template",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [],
        admin_access: true,
        user_access: false,
        employee_access: false,
        required_authentication: true,
    },
    // log status
    {
        activity_type: activityTypes.Log,
        module: moduleTypes.Priorities,
        activity_name: activityName.logPriority,
        activity_code: activityCode.logPriority,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/priorities/log",
        status: true,
        form_params: [],
        search_params: [
            {
                title: "id",
                value: "id",
                allowed_values: [],
                datatype: datatypes.String,
                search_type: searchTypes.Exact,
                is_active: true,

                admin_access: true,
                user_access: true,
                employee_access: true,
            },
            {
                title: "event_type_name",
                value: "event_type",
                allowed_values: [],
                datatype: datatypes.String,
                search_type: searchTypes.Exact,
                is_active: true,

                admin_access: true,
                user_access: true,
                employee_access: true,
            },
            {
                title: "response_body_error_status",
                value: "response_body.error",
                allowed_values: [],
                datatype: datatypes.Boolean,
                search_type: searchTypes.Exact,
                is_active: true,

                admin_access: true,
                user_access: true,
                employee_access: true,
            },
            {
                title: "executed_by_name_like",
                value: "executed_by.first_name",
                allowed_values: [],
                datatype: datatypes.String,
                search_type: searchTypes.Partial,
                is_active: true,

                admin_access: true,
                user_access: true,
                employee_access: true,
            },
            {
                title: "executed_by_email_like",
                value: "executed_by.user_email",
                allowed_values: [],
                datatype: datatypes.String,
                search_type: searchTypes.Partial,
                is_active: true,

                admin_access: true,
                user_access: true,
                employee_access: true,
            },
        ],
        access_params: {
            admin_access: { type: AccessType.ALL, keys: [] },
            user_access: { type: AccessType.ALL, keys: [] },
            employee_access: { type: AccessType.ALL, keys: [] },
        },

        control_params: [],
        payload_params: [],
        admin_access: true,
        user_access: false,
        employee_access: false,
        required_authentication: true,
    },
];

export default priorityApiData;
