export enum moduleTypes {
  Authentication = "authentication",
  Statuses = "statuses",
  Roles = "roles",
  Users = "users",
  Countries = "countries",
  Providers = "providers",
  Uploads = "uploads",
  Jobs = "jobs",
  Applications = "applications",
  Notifications = "notifications",
  Regions = "regions",
  Districts = "districts",
  AuthenticationSession = "authentication_session",
  Services = "services",
  Declaimers = "declaimers",
  Priorities = "priorities",
}
