export enum tableName {
  User = "users",
  Status = "status",
  ActivityLog = "activity_logs",
  Api = "apis",
  Tokens = "tokens",
  Otp = "otps",
  Countries = "countries",
  Regions = "regions",
  Documents = "documents",
  Providers = "providers",
  Districts = "districts",
  Suburbs = "suburbs",
  Declaimers = "declaimers",
  Roles = "roles",
  RefreshSessions = "refresh_sessions",
  Priority = "priorities",
  Units = "units",
  Services = "services",
  ServiceLocations = "service_locations",
}
